version: '3.9'
services:
  db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: school-registry-backend
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "6060:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

  frontend:
    build:
      context: ../school-registry-frontend/
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    ports:
      - "3000:80"
networks:
  name:
    external: true
volumes:
  db:
